use employees;
select * from employees where first_name in ('Irene', 'Vidya', 'Maya') order by first_name;
select * from employees where first_name in ('Irene', 'Vidya', 'Maya') order by first_name, last_name;
select * from employees where first_name in ('Irene', 'Vidya', 'Maya') order by last_name, first_name;
select * from employees where last_name like 'e%';
SELECT * from employees WHERE last_name LIKE 'e%' ORDER BY emp_no;
SELECT * FROM employees WHERE last_name LIKE 'e%' ORDER BY emp_no DESC;
select * from employees where last_name like '%q%';
select * from employees where first_name in ('Irene', 'Vidya', 'Maya') and gender like '%m%';
select * from employees where last_name like 'e%' or last_name like '%e';
select * from employees where last_name like '%q%' and last_name not like '%qu%';
